#!/bin/bash


clear

kdir="Create_a_directory"
ouch="Create_a_file"
y="Install_a_package_and_software"
estart="Reboot_your_pc"
dae="Check_current_date_and_time"
oogle="search_on_google"
ser="Create_a_user_and_password"
song="play_song"
top="Google_top_5_url"


select comm in $kdir $ouch $y $estart $dae $oogle $ser $song $top $fb
do
	if [ "$comm" = "$kdir" ]
	then
		read -p "Enter your directory name :- " rrrr
		
		mkdir $rrrr
		break
	fi
	
	if [ "$comm" = "$ouch" ]
	then
		read -p "Enter your file name :- " file

		touch $file
		break
	fi
	
	if [ "$comm" = "$y" ]
	then
		read -p "Enter the package and software name :- " soft

		yum install $soft
		break
	fi
	
	if [ "$comm" = "$estart" ]
	then
		sudo reboot
	fi
	
	if [ "$comm" = "$dae" ]
	then
		date
		break
	fi

	if [ "$comm" = "$oogle" ]
	then
		read -p "Google seach :- " uurl
                googler $uurl
                break
	fi
	
	if [ "$comm" = "$ser" ]
	then
		read -p "Enter your user to create :- " user
		
		useradd $user
		
		read -m "Enter the password :- " pass
		
		passwd $user
		
		$pass

		break
	fi

	if [ "$comm" = "$song" ]
      	then
                read -p "Enter the path of Music" music
                play $music
                break
        fi

        if [ "$comm" = "$top" ]
        then
                read -p "Google seach :- " topurl
                googler --count=8 $topurl
                break
        fi

done
